stephenh/ts-proto

- src/types.ts
Adds remaining types to typeMap handle simplifying full list of wrapper types found at: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto
> Adds remaining wrapper types to valueType map

- src/types.ts
First of all, thanks for ts-proto, I really appreciate finally having a protoc plugin that generates typescript interfaces instead of classes!
When a field in a .proto file has a map type and a non-camelCase name (e.g. `map<string, TraceSourceInfo> trace_source_info = 10;`), the generated code for this field was typed to an array instead of an index-signature object. Instead of relying on the string comparison of type and field name (which fails when the field name is snake_case), the relevant types can be looked up from the type map.
I didn't fully understand the test infrastructure, so I couldn't add any unit tests unfortunately.
> fix map type detection when field name is not camelCase

- simple.proto
- src/main.ts
- src/sourceInfo.ts
- src/types.ts
- src/utils.ts
Added comments from fileDescriptor.sourceCodeInfo to enums, message interfaces, and services.
Should resolve issue 23
https://github.com/stephenh/ts-proto/issues/23
> #23 - Add source comments from file descriptor

- integration/simple-long-string/simple.ts
- integration/simple-long/simple.ts
- integration/simple-snake/simple.ts
- integration/simple/simple-json-test.ts
- integration/simple/simple.ts
- integration/vector-tile/__snapshots__/vector-tile-test.ts.snap
- integration/vector-tile/vector_tile.ts
- src/main.ts
Fixes https://github.com/stephenh/ts-proto/issues/41
Update enum default to be `UNRECOGNIZED` / `-1` to be consistent with how java generates enums.
e.g.
```java
public enum ChangeType implements ProtocolMessageEnum {
ADDED(0),
REMOVED(1),
MODIFIED(2),
UNRECOGNIZED(-1);
```
> Add unrecognized enum value

- integration/batching-with-context/batching.ts
- integration/batching/batching.ts
- integration/point/point.ts
- integration/simple-long-string/google/protobuf/timestamp.ts
- integration/simple-long-string/google/protobuf/wrappers.ts
- integration/simple-long-string/import_dir/thing.ts
- integration/simple-long-string/simple.ts
- integration/simple-long/google/protobuf/timestamp.ts
- integration/simple-long/google/protobuf/wrappers.ts
- integration/simple-long/import_dir/thing.ts
- integration/simple-long/simple.ts
- integration/simple-proto2/simple.ts
- integration/simple-snake/google/protobuf/timestamp.ts
- integration/simple-snake/google/protobuf/wrappers.ts
- integration/simple-snake/import_dir/thing.ts
- integration/simple-snake/simple.ts
- integration/simple/google/protobuf/timestamp.ts
- integration/simple/google/protobuf/wrappers.ts
- integration/simple/import_dir/thing.ts
- integration/simple/simple.ts
- integration/types-with-underscores/file.ts
- integration/vector-tile/__snapshots__/vector-tile-test.ts.snap
- integration/vector-tile/vector-tile-test.ts
- integration/vector-tile/vector_tile.ts
- package.json
- src/main.ts
This PR makes a small tweak to the `decode()` method so that it can accept an input type of `Uint8Array | Reader` (vs just `Reader` previously). 
You'll want to view this PR by commit. The 1st commit contains the actual changes. And the 2nd contains all the jitter caused by integration tests updating themselves to reflect the new method signature.
Also, I wasn't sure if your build process / CI auto ticks the package version, so I included a version bump in the PR as well.
> Allow Uint8Arrays / Buffers to be passed to decode() directly

- package.json
- src/main.ts
- tsconfig.json
First off let me say I am very grateful to see NestJS support here, so thanks! I've been doing similar things in a custom tool alongside your ts-proto package but glad to see it in here now.
This fixes the controller methods decorator. Prior to this fix it was using the wrong decorator for certain types of methods.
Given the following proto that demonstrates all possible combinations of rpcs:
```proto
service GreeterService {
rpc SayHello (HelloRequest) returns (HelloReply) {}
rpc SayHelloToAll (stream HelloRequest) returns (stream HelloReplyMessage) {}
rpc MonitorHellos (MonitorHelloRequest) returns (stream MonitorHelloResponse) {}
rpc MonitorHellosWithSnapshot (MonitorHelloRequest) returns (stream MonitorHelloResponseOrSnapshot) {}
rpc BroadcastHellos (stream HelloRequest) returns …
```
> fix(nestjs): fixes grpc controller decorator

- integration/simple-long-string/simple.ts
- integration/simple-long/simple.ts
- integration/simple-snake/simple.ts
- integration/simple/simple.ts
- src/main.ts
- src/types.ts
addresses https://github.com/stephenh/ts-proto/issues/80
> repeated google.protobuf.FoobarValue fields should translate to Foobar[], not Array<Foobar | undefined>

- src/main.ts
As per #94 which is closed. `useContext` didn't seem to work properly because it was not adding DataLoader interface. This makes sure that if flag is passed it will properly generate and insert interface into generated output.
> Fix DataLoader interface not being added

- integration/codegen.sh
- integration/oneof-properties/oneof.ts
- integration/oneof-unions/oneof.ts
- integration/simple-long-string/simple.ts
- integration/simple-long/simple.ts
- integration/simple-optionals/simple.ts
- integration/simple-proto2/simple.ts
- integration/simple-snake/simple.ts
- integration/simple/simple.ts
- integration/vector-tile/__snapshots__/vector-tile-test.ts.snap
- integration/vector-tile/vector_tile.ts
- src/case.ts
- src/main.ts
- src/types.ts
Previously we used an enum-like pattern so that we could attach
methods like toJSON/fromJSON to the enum itself, i.e.
StateEnum.fromJSON.
This was done out of a) convenience b/c we already knew where the
`StateEnum` came from (i.e. had it imported) and b) in-theory
developer ergonomics for calling the `StateEnum.fromJSON` method.
However, a) is easy to fix with just trying harder, i.e. a new
getEnumMethod that can find top-level functions for a given enum,
i.e. stateEnumFromJSON is in module x/y/z.
And b) is not really a factor b/c developers should rarely serialize
an enum directly and are probably/basically always working with
MessageFoo.to/fromJSON, and it's only the internals of
MessageFoo.to/fromJSON that have to know where the enum functions
live/how to call them.
So, this PR …
> Go back to use `enum` keyword for enums.

- integration/grpc-web/example.ts
- src/generate-grpc-web.ts
"import =" is not supported by @babel/plugin-transform-typescript (https://github.com/babel/babel/issues/7062) so the grpc-web generated code has compilation issues for Create React App and Parcel 2 compiled browser applications. 
It seems this syntax can be trivially avoided which seems preferable.
> Avoid "import =" in grpc-web code generation

- README.markdown
- integration/nestjs-simple/google/protobuf/timestamp.ts
- integration/nestjs-simple/hero.proto
- integration/nestjs-simple/hero.ts
- integration/nestjs-simple/nestjs-project/app.module.ts
- integration/nestjs-simple/nestjs-project/hero.controller.ts
- integration/nestjs-simple/nestjs-project/main.ts
- integration/nestjs-simple/nestjs-simple-test.ts
- integration/nestjs-simple/sample-service.ts
- src/main.ts
- src/types.ts
- src/utils.ts
The mapping of google.protobuf.Timestamp to Date in the generated interfaces does not seem compatible with NestJS which does not serialize these as Dates.
> Make Timestamp/Date mapping optional

- integration/batching-with-context/batching.ts
- src/generate-services.ts
- src/main.ts
Adds an optional `rpcDataLoaderOptions` field to `ctx` which would allow us to pass options to the data loader during runtime to, for instance, disable caching for a particular request.
> Add way to pass data loader options

- src/main.ts
There seemed to be one left over unscoped when `unrecognizedEnum=false`.
> Fix left over globalThis.Error scoping when using unrecognizedEnum=false

- integration/simple-deprecated-fields/simple.ts
- src/utils.ts
Currently, deprecated fields without any comments are not marked as deprecated.
This PR fixes this by adding a comment regardless of existing comments in proto - if necessary.
> fix: add deprecated comment when there are not other comments

- src/types.ts
Currently the default value for enums is 0, such that the `stringEnums` option is not enforced.
> Support stringEnums in fromJson default value

- src/generate-services.ts
I just hit against this typo. Haven't looked into the test structure yet, but happy to add one if you point me to the right location.
> Fix typo in generate-services > generateRegularRpcMethod

- src/main.ts
fromTimestamp function definition was missing when outputJsonMethods is true but outputEncodeMethods is false.
> Add missing fromTimestamp function 

- integration/avoid-import-conflicts/simple.ts
- integration/barrel-imports/foo.ts
- integration/batching-with-context/batching.ts
- integration/batching/batching.ts
- integration/grpc-web-go-server/example.ts
- integration/grpc-web-no-streaming-observable/example.ts
- integration/grpc-web-no-streaming/example.ts
- integration/point/point.ts
- integration/simple-deprecated-fields/simple.ts
- integration/simple-long-string/simple.ts
- integration/simple-long/simple.ts
- integration/simple-optionals/import_dir/thing.ts
- integration/simple-optionals/simple.ts
- integration/simple-optionals/thing.ts
- integration/simple-snake/import_dir/thing.ts
- integration/simple-snake/simple.ts
- integration/simple-unrecognized-enum/import_dir/thing.ts
- integration/simple-unrecognized-enum/simple.ts
- integration/simple/import_dir/thing.ts
- integration/simple/simple.ts
- src/main.ts
I came across this when working on #213.
Since `${defaultValue(ctx, field)}` is always `undefined` for messages, this generates the ame test code twice.
> Remove redundant default check for messages

- integration/nestjs-metadata-observables/hero.ts
- integration/nestjs-metadata-restparameters/hero.ts
- integration/nestjs-metadata/hero.ts
- integration/nestjs-restparameters/hero.ts
- integration/nestjs-simple-observables/hero.ts
- integration/nestjs-simple-restparameters/hero.ts
- integration/nestjs-simple/hero.ts
- integration/simple-esmodule-interop/tsconfig.json
- integration/tsconfig.json
- src/generate-nestjs.ts
- tsconfig.json
Fixes #235 
Having tsconfig `strict: true` and `noImplicitAny: false` is not recommended. See [this comment](https://github.com/Microsoft/TypeScript/issues/18687#issuecomment-331469718)
With `noImplicitAny` enabled, `nestjs-simple-restparameters` catches this failure
> Fix implicit any

- integration/grpc-web-no-streaming-observable/example.ts
- integration/grpc-web-no-streaming/example.ts
- integration/grpc-web/example.ts
- src/generate-grpc-web.ts
I had some issues with using the generated code in combination with
babel-loader in my webpack setup. The grpc-web output was producing
references to .d.ts files within @improbable-eng/grpc-web. This broke
compilation with babel-loader since that has no concept of type
definition files.
This fixes that by simply using the fully qualified types which are
accepted by babel-loader.
> Use qualified imports for grpc-web types

- integration/type-registry/typeRegistry.ts
- src/generate-type-registry.ts
I started integrating `ts-proto`, employing the new type registry feature, and discovered that the `$type` field was missing from `MessageType` type. This PR adds the missing field.
> fix: improve type registry types

- integration/codegen.ts
- src/plugin.ts
According to doc comments in `plugin.proto` from Google:
```
// The .proto files that were explicitly listed on the command-line.  The
// code generator should generate code only for these files.  Each file's
// descriptor will be included in proto_file, below.
repeated string file_to_generate = 1;
```
> fix: Only generate files in fileToGenerate

- integration/batching-with-context/batching.ts
- integration/batching/batching.ts
- integration/grpc-web-go-server/example.ts
- integration/grpc-web-no-streaming-observable/example.ts
- integration/grpc-web-no-streaming/example.ts
- integration/grpc-web/example-test.ts
- integration/grpc-web/example.ts
- integration/meta-typings/simple.ts
- integration/no-proto-package/no-proto-package.ts
- integration/simple-optionals/simple.ts
- integration/simple-snake/simple.ts
- integration/simple-unrecognized-enum/simple.ts
- integration/simple/simple-service-test.ts
- integration/simple/simple.ts
- src/generate-grpc-web.ts
- src/generate-services.ts
This makes it easier to pass around service function references. For example, with this change you can use [react-query](https://react-query.tanstack.com/guides/mutations) directly: `useMutation(fooClient.bar);`
> feat: Bind service methods to class

- README.markdown
- integration/codegen.ts
- src/options.ts
- src/plugin.ts
- tests/options-test.ts
Fixes #294.
This commit puts changes from #283 behind the flag.
> feat: implemented emitImportedFiles flag

- integration/bytes-as-base64/message.ts
- integration/bytes-node/point.ts
- integration/oneof-properties/oneof.ts
- integration/oneof-unions/oneof.ts
- integration/simple-long-string/google/protobuf/wrappers.ts
- integration/simple-long/google/protobuf/wrappers.ts
- integration/simple-optionals/google/protobuf/wrappers.ts
- integration/simple-snake/google/protobuf/wrappers.ts
- integration/simple-unrecognized-enum/google/protobuf/wrappers.ts
- integration/simple/google/protobuf/wrappers.ts
- integration/simple/simple.ts
- src/main.ts
This PR fixes compilation of generated TypeScript files with enabled [Checked Indexed Access](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#checked-indexed-accesses---nouncheckedindexedaccess).
> fix: Fix TypeScript errors when compiling with `noUncheckedIndexedAccess`

- protos/.gitignore
- protos/build.sh
- protos/package.json
When importing `ts-proto-descriptors` into a typescript project, it will try to import the typescript source code, and not the generated javascript. This is an issue when the dependent project's `tsconfig` file does not agree with the `tsconfig` for `ts-proto`.
For example, my project depends on `ts-proto-descriptors` has a `tsconfig` that has enabled `esModuleInterop`. But the `ts-proto` `tsconfig` does not have this option set, meaning the `ts-proto-descriptors` source is not compatible with my project and throws the following typescript errors:
```
node_modules/ts-proto-descriptors/google/protobuf/compiler/plugin.ts:609:5 - error TS2367: This condition will always return 'true' since the types 'Constructor<Long>' and '{ default: LongConstructor; prototype: Long; MAX_UNSIGNED_VALUE: …
```
> fix: tsconfig conflict issue that occurs with ts-proto-descriptors

- integration/grpc-web/example.ts
- src/generate-grpc-web.ts
I found that once a server stream is opened, there is no way to close it. Unsubscribing from the observable would not close the connection between the browser and the server.
This change adds a handler on the observer that will call the grpc.invoke's `close`, which will close the connection between the browser and the server.
> fix: close server stream on observer unsubscribe

- README.markdown
See #333.
Provides basic instructions for integration ts-proto with Gradle and the protobuf-gradle-plugin. The provided snippet does not address installation of ts-proto or usage of the generated code. My own use case involves automated publishing through Gradle, but one could presumably consume the code locally by pointing `tsconfig.json` to the output directory.
Feel free to modify the location within the readme and the wording.
Thanks for a great tool!
> docs: Add Gradle invocation instructions

- src/case.ts
- tests/case-test.ts
> fix: Field starting with '_' generates an interface property starting with 'undefined'

- README.markdown
- src/generate-nestjs.ts
- src/main.ts
- src/options.ts
- src/utils.ts
- tests/options-test.ts
Fixes https://github.com/stephenh/ts-proto/issues/349
Added some minor refactoring to extract out the service option to its own Enum.
> feat: Service generation option

- integration/batching-with-context/batching.ts
- integration/batching/batching.ts
- integration/grpc-web-go-server/example.ts
- integration/lower-case-svc-methods/math.ts
- integration/meta-typings/simple.ts
- integration/no-proto-package/no-proto-package.ts
- integration/simple-optionals/simple.ts
- integration/simple-snake/simple.ts
- integration/simple-unrecognized-enum/simple.ts
- integration/simple/simple.ts
- src/generate-grpc-web.ts
- src/generate-services.ts
- src/main.ts
- src/types.ts
I just went ahead and implemented my proposal from #372.
This should make it possible to do streaming RPCs, given that the user's Rpc implementation implements a few extra methods.
Not sure why the Reader/Writer order was changed in the generated files. I'm assuming it's because I changed some calling order, but I didn't investigate.
> feat: Streaming support

- integration/grpc-web/client-ts.ts
I've just spent about an hour trying to figure out why it wasn't working because I didn't realise that this just applies to a node environment. (Now that I know, it's quite obvious).
Since this is the reference for `grpc-web` I assume that many people will just copy this and a comment like this might be helpful.
> docs: Add note about transport

- integration/batching-with-context/batching.ts
- integration/batching/batching.ts
- integration/bytes-as-base64/message.ts
- integration/bytes-node/point.ts
- integration/grpc-js/google/protobuf/wrappers.ts
- integration/grpc-web-go-server/example.ts
- integration/grpc-web-no-streaming-observable/example.ts
- integration/grpc-web-no-streaming/example.ts
- integration/grpc-web/example.ts
- integration/lower-case-svc-methods/math.ts
- integration/oneof-properties/oneof.ts
- integration/oneof-unions/oneof.ts
- integration/simple-long-string/google/protobuf/wrappers.ts
- integration/simple-long/google/protobuf/wrappers.ts
- integration/simple-long/simple.ts
- integration/simple-optionals/google/protobuf/wrappers.ts
- integration/simple-optionals/simple.ts
- integration/simple-snake/google/protobuf/wrappers.ts
- integration/simple-snake/simple.ts
- integration/simple-string-enums/simple.ts
- integration/simple-unrecognized-enum/google/protobuf/wrappers.ts
- integration/simple-unrecognized-enum/simple.ts
- integration/simple/google/protobuf/wrappers.ts
- integration/simple/simple.ts
- integration/use-date-string/use-date-string.ts
- integration/use-date-true/use-date-true.ts
- integration/vector-tile/vector_tile.ts
- src/main.ts
This uses `map` to initialize lists, such that all cases can be handled within one assignment. `if (object.ids !== undefined && object.ids !== null) {` was replaced with `object.ids ?? []` to save nesting depth and code size.
> feat: Initialize lists with map

- integration/batching-with-context/batching.ts
- integration/batching/batching.ts
- integration/simple-long/simple.ts
- integration/simple-optionals/simple.ts
- integration/simple-snake/simple.ts
- integration/simple-unrecognized-enum/simple.ts
- integration/simple/simple.ts
- integration/struct/google/protobuf/struct.ts
- integration/use-date-string/use-date-string.ts
- integration/use-date-true/use-date-true.ts
- integration/value/google/protobuf/struct.ts
- src/main.ts
This follows the same idea as previous PRs for fromJSON/fromPartial: have exactly one assignment per field.
The explicit typing in reduce is necessary to avoid that TS infers `{}` as the output/accumulator type. `${fieldType}` could be replaced with `typeof message.outputField` but then in https://github.com/stephenh/ts-proto/pull/402 the output field might become optional but `${fieldType}` should not change.
> feat: Improve map reading (fromJSON/fromPartial)

- integration/simple-long/simple.ts
- src/main.ts
for improved robustness regarding already parsed objects
as discussed [here](https://github.com/stephenh/ts-proto/pull/395#issuecomment-975525988)
> fix: use Long.fromValue instead of Long.fromString

- README.markdown
I added a small description of what the generic definitions are and added a link to [nice-grpc](https://github.com/deeplay-io/nice-grpc) as an example of a library that utilizes this feature.
> docs: improve readme section on generic service definitions

- src/types.ts
> fix: Unwrap google.protobuf.BytesValue to Buffer when env=node

- .gitattributes
- aliases.sh
- docker-compose.yml
Restores the dockerized version of `protoc`, for standalone use, as documented under [Readme.md#development](https://github.com/stephenh/ts-proto#development)
`Dockerfile` and `yarn` commands not touched. Added a default _docker-compose_ mount of `$PWD:/host`, this should not affect other uses of the container as the container does not automatically enter this directory, and the project directory is mounted in case $PWD is not set (e.g. when running without TTY)
> fix: dockerized protoc aliases

- README.markdown
- integration/simple-snake/import_dir/thing.ts
- integration/simple-snake/simple.ts
- src/case.ts
- src/options.ts
- src/utils.ts
Restores `snakeToCamel=false` functionality due the breaking change introduced by #210. Implements changes as per the discussion in #423. 
Now `snakeToCamel: boolean` is `snakeToCamel: boolean | string` and accepts string input too `keys, json`.
This is how the option will be mapped:
- snakeToCamel=true (the default) --> ["keys", "json"]
- snakeToCamel=false --> []
- snakeToCamel=keys --> ["keys"], use camel cased message keys, but still snake case in to/from JSON
- snakeToCamel=json --> ["json"], use proto3-spec camel casing in to/fromJSON, but still snake case in message keys
- snakeToCamel=keys,json --> ["keys","json"]
Resolves #423
> fix: support mutliple options in snakeToCamel flag 

- README.markdown
On first glance, I thought "Protobuf JS format" meant the `protobufjs` format, which is not spec-compliant. I edited to clarity. I also changed `i.e.` to `e.g.` because the former implies that's the only thing that makes the method spec-compliant. I imagine it correctly encodes all the other types as well, not just `Timestamp`?
> docs: Clarify fromJSON/toJSON format in README

- integration/codegen.ts
- integration/watch.ts
- package.json
Attempting to further improve developer workflow. Hoping - but not sure - that I didn't go too far, I would like feedback on these additions separately.
- Let `yarn watch` monitor source directories as well
- Tell the user what to do when the sources change
- Press Enter to recompile ALL proto files
- Run `yarn watch TEST1 TEST2` to automatically recompile TEST1 and TEST2 when sources change
```
$ yarn watch -h
Watches the integration directory for changes and regenerates .bin and .ts files.
Watches the src directory and regenerates given TEST files.
Usage:
$ yarn watch [options] [TEST, TEST2, ...]
$ ts-node watch.ts [options] [TEST, TEST2, ...]
Options:
-h, --help    Show this help message.
--polling     Use polling instead of native watchers.
TEST          Regenerate the specified …
```
> feat: yarn watch updates (specified) tests when source files change

- src/generate-grpc-js.ts
Do not generate client stub and constructor when `outputServices=grpc-js` and `outputClientImpl=false`
> fix: respect generateClientImpl=false in grpc-js (#471)

- protos/build.sh
- protos/google/protobuf/compiler/plugin.ts
- protos/google/protobuf/descriptor.ts
- protos/package.json
- protos/yarn.lock
Builds upon #473 to add support for options in #437.
I had to also enable `--downlevelIteration` tsc flag as that is now a requirement due to looping over `Uint8Array`.
The tests will most likely need to be updated after the package is published.
> feat: enable unknown fields for descriptor protos

- package.json
- yarn.lock
Fixes #480
Per discussion here:
https://github.com/stephenh/ts-proto/pull/479#issuecomment-1015438971
Because of `oneofIndex=0` being ambiguous about "is this set? or is this the first oneof?" and ts-proto's current like of `hazzer` methods, we need to pin to a specific version of ts-proto-descriptors that was built with temporary `hazzer` functionality that has since been reverted.
> fix: Pin ts-proto-descriptors to 1.3.1.

- README.markdown
- protos/build.sh
- protos/google/protobuf/compiler/plugin.ts
- protos/google/protobuf/descriptor.ts
- protos/package.json
- protos/yarn.lock
This builds upon #484 to fix any issues with failing property checks.
I also added the description of the option in the readme I forgot in the previous PR.
> feat: enable prototype for defaults for ts-proto-descriptors

- integration/bytes-as-base64/message.ts
- integration/bytes-node/google/protobuf/wrappers.ts
- integration/bytes-node/point.ts
- integration/grpc-js/google/protobuf/wrappers.ts
- integration/oneof-properties/oneof.ts
- integration/oneof-unions/oneof.ts
- integration/simple-long-string/google/protobuf/wrappers.ts
- integration/simple-long/google/protobuf/wrappers.ts
- integration/simple-optionals/google/protobuf/wrappers.ts
- integration/simple-prototype-defaults/google/protobuf/wrappers.ts
- integration/simple-prototype-defaults/simple.ts
- integration/simple-snake/google/protobuf/wrappers.ts
- integration/simple-unrecognized-enum/google/protobuf/wrappers.ts
- integration/simple/google/protobuf/wrappers.ts
- integration/simple/simple.ts
- integration/use-optionals-all/test.ts
- integration/value/google/protobuf/wrappers.ts
- src/main.ts
Otherwise, TypeScript 4.6.2 complains:
TS2569: Type 'Uint8Array' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
184 | function base64FromBytes(arr: Uint8Array): string {
185 |   const bin: string[] = [];
> 186 |   for (const byte of arr) {
|                      ^^^
> fix: Use Uint8Array.forEach in base64FromBytes

- README.markdown
Some shell scripts use the realpath command, which will report an error...
> chore: OS X requires coreutils to be installed

- README.markdown
I think it was the intention to say messages rather than primtives here.
> docs: In README change copy-paste mistake of primitives to messages

- CHANGELOG.md
- integration/generic-metadata/hero.ts
- integration/generic-service-definitions-and-services/simple.ts
- integration/generic-service-definitions/simple.ts
- integration/grpc-js/simple.ts
- integration/use-date-true/use-date-true.ts
- src/generate-generic-service-definition.ts
- src/generate-grpc-js.ts
When exporting a service or service definition, also export it as a
type. Previously, you would have to import the value then `typeof` off
of it which is cumbersome. Automate this as it has no runtime overhead
and seems more intuitive.
Before:
```ts
export const TestDefinition = {
name: 'Test',
fullName: 'simple.Test',
methods: {
…
},
} as const;
```
After:
```ts
export type TestDefinition = typeof TestDefinition;
export const TestDefinition = {
name: 'Test',
fullName: 'simple.Test',
methods: {
…
},
} as const;
```
> feat: include service and definition types with implementations

- integration/const-enum/const-enum.ts
- integration/options/google/protobuf/descriptor.ts
- integration/options/options.ts
- integration/options/something/something.ts
- integration/simple-prototype-defaults/simple.ts
- integration/simple-string-enums/simple.ts
- integration/simple/simple.ts
- src/main.ts
Our grpc-gateway service returns enums as strings in JSON, but we want to convert those to numeric enums in the client. It works fine for enum fields in messages (which use the enum's `fromJSON` method), but not for enum values in maps (which currently just generate a type cast).
This PR changes the generator to use the enum's `fromJSON` method instead of a type cast for map values.
> fix: Use `fromJSON` methods to deserialize enum map values

- .github/workflows/buf.yml
- README.markdown
- integration/options/google/protobuf/descriptor.ts
- integration/options/options.ts
- integration/options/something/something.ts
- ts-proto.Dockerfile
Per [Buf](https://docs.buf.build)'s website:
> ## Buf is building a modern Protobuf ecosystem
> Our tools address many of the problems above, ultimately allowing you to redirect much of your time and energy from managing Protobuf files to implementing your core features and infrastructure.
> ### The `buf` CLI
> The buf CLI enables you to create consistent Protobuf APIs that preserve compatibility and comply with best practices. The tool is currently available on an open-source basis. The buf CLI incorporates these components to help you create consistent Protobuf APIs:
> - A new developed [high-performance Protobuf compiler](https://docs.buf.build/reference/internal-compiler).
> - A [linter](https://docs.buf.build/lint/overview) that enforces good API design choices and structure.
> - A …
> feat: Official Buf Plugin

- integration/simple-esmodule-interop/package.json
- integration/simple-esmodule-interop/yarn.lock
- integration/unknown-fields/google/protobuf/compiler/plugin.ts
- integration/unknown-fields/google/protobuf/descriptor.ts
- integration/unknown-fields/options.ts
- integration/unknown-fields/something/something.ts
- package.json
- src/main.ts
- yarn.lock
Updates to TypeScript 4.7.x (latest).
This requires an update to ts-proto-descriptors, to release:
1. Release ts-proto-descriptors version 1.7.0.
2. Update package.json with ts-proto-descriptors version.
3. Publish ts-proto update.
cc @stephenh please release ts-proto-descriptors 1.7.0 from this PR and I'll update the commit.
> refactor: update to typescript 4.7.4

- integration/codegen.ts
- integration/import-suffix/child.pb.ts
- integration/import-suffix/google/protobuf/timestamp.pb.ts
- integration/import-suffix/parent.pb.ts
- integration/simple-esmodule-interop/simple.ts
- src/generate-services.ts
- src/generate-type-registry.ts
- src/main.ts
- src/options.ts
- src/schema.ts
- src/utils.ts
> fix: internal packages now takes suffix and esm opt.

- README.markdown
resolves `Failure: node_modules/protobufjs/google/api/annotations.proto:5:8:google/api/http.proto: does not exist`
Note: This assumes `buf.yaml` is in the top-level project directory, next to `node_modules`
> docs: add `node_modules` exclusion

- integration/grpc-web/example.ts
- src/generate-grpc-web.ts
This PR introduces metadata support in Stream (invoke) during catch as in Unary. It's required to read gRPC richer errors.
S
> feat: add meta-data to stream error

- integration/fieldmask/google/protobuf/field_mask.ts
- src/main.ts
Fixes the following type error:
```
../protos/dist/google/protobuf/field_mask.ts:274:5 - error TS2741: Property '$type' is missing in type '{ paths: string[]; }' but required in type 'FieldMask'.
274     return { paths: paths };
~~~~~~~~~~~~~~~~~~~~~~~~
../protos/dist/google/protobuf/field_mask.ts:209:3
209   $type: 'google.protobuf.FieldMask';
~~~~~
'$type' is declared here.
```
When ts-proto is run with `outputTypeRegistry=true`.
> fix: fieldmask wrap method with type registry

- integration/bytes-as-base64/message.ts
- integration/bytes-node/google/protobuf/wrappers.ts
- integration/bytes-node/point.ts
- integration/grpc-js/google/protobuf/wrappers.ts
- integration/nice-grpc/google/protobuf/wrappers.ts
- integration/oneof-properties/oneof.ts
- integration/oneof-unions/oneof.ts
- integration/simple-long-string/google/protobuf/wrappers.ts
- integration/simple-long/google/protobuf/wrappers.ts
- integration/simple-optionals/google/protobuf/wrappers.ts
- integration/simple-prototype-defaults/google/protobuf/wrappers.ts
- integration/simple-prototype-defaults/simple.ts
- integration/simple-snake/google/protobuf/wrappers.ts
- integration/simple-unrecognized-enum/google/protobuf/wrappers.ts
- integration/simple/google/protobuf/wrappers.ts
- integration/simple/simple.ts
- integration/simple/utils.ts
- integration/use-optionals-all/test.ts
- integration/value/google/protobuf/wrappers.ts
- src/main.ts
I didn't change the browser code but `for .. of` would probably be more performant than `forEach` on it
> perf: Faster base64FromBytes & bytesFromBase64 on Node.JS

- src/case.ts
- src/utils.ts
- tests/case-test.ts
Previously we only checked jsonName if snakeToCamel=json was enabled,
b/c protobuf _always_ set jsonName to the camelized key name OR the
jsonName attribute value.
Because of this, we couldn't do logic like "if jsonName is explicitly
set, use that, otherwise keep the field name as-is".
Now we guess about whether jsonName is explicitly set by doing our
own snake-field-name -> camel-json-name, and if our camel-json-name
matches jsonName, then we assume the user has _not_ set jsonName,
and we should keep using snake-field-name.
But if those two values, camel-json-name and jsonName, are different,
then the user has probably manually set jsonName in the proto file,
and we'll use that instead.
Fixes #635
> fix: Use jsonName even with snakeToCamel=false.

- README.markdown
tldr: envoy uses nghttp2, which reports `invalid frame: Violation in HTTP messaging rule on stream 1`
Long Story: If you use this example in a server node.js process in Kubernetes with an Istio Service Mesh, envoy will report something like
```
│ 2022-08-29T12:53:55.616404Z    debug    envoy http2    [C398] updating connection-level initial window size to 268435456                                                                                                                                                                                                   │
│ 2022-08-29T12:53:55.616663Z    debug    envoy http2    [C398] invalid frame: Violation in HTTP messaging rule on stream 1
```
if you try to call an gRPC request. Sadly, there is basically no documentation at all available for this …
> docs(readme): fix gRPC example

- src/options.ts
So because the test for the `M` opt is really the output of `yarn build:test`
I didn't catch a bug I introduced in my last iteration of refactoring.
In `options`, `M` is `undefined` so passing `M` opts doesn't work
because it'll try `options.M['...']` and `options.M` is undefined.
`options` should start out with the default `M`.
Apologies for the bug!
> fix(options): initializes M opt to empty object

- README.markdown
- integration/nice-grpc/simple.ts
- src/generate-nice-grpc.ts
This PR proposes two changes:
- When generating the `nice-grpc` output, the `CallContext` and `CallOptions` are not needed at runtime, so a `type`-only import is sufficient.
- Format code step in the documentation.
Closes #677
----
Great lib, thank you!
> feat: Import CallContext and CallOptions as type

- integration/async-iterable-services/simple.ts
- integration/avoid-import-conflicts/simple.ts
- integration/batching-with-context/batching.ts
- integration/batching/batching.ts
- integration/generic-metadata/hero.ts
- integration/grpc-web-go-server/example.ts
- integration/lower-case-svc-methods/math.ts
- integration/meta-typings/simple.ts
- integration/no-proto-package/no-proto-package.ts
- integration/options/options.ts
- integration/simple-optionals/simple.ts
- integration/simple-prototype-defaults/simple.ts
- integration/simple-snake/simple.ts
- integration/simple-unrecognized-enum/simple.ts
- integration/simple/simple-service-test.ts
- integration/simple/simple.ts
- integration/unknown-fields/options.ts
- integration/use-date-true/use-date-true.ts
- src/generate-services.ts
Currently the service identifier is the fully qualified "fullName" of the service, for example, "simple.Echoer"
This identifier is hard-coded in the auto-generated client with string literals.
Instead, allow overriding the service ID with a new optional argument in the client constructor, default the service ID to the fullName, and store the ID in a read-only field on the client object.
This allows the user to override the service ID if desired while still maintaining the old behavior otherwise.
> feat(client): allow overriding the service identifier

- README.markdown
- src/options.ts
- src/visit.ts
- tests/options-test.ts
Adding option to change out the types that are generated. 
Example Proto:
```ProtoBuf
message Box {
message Element {
message Image {
enum Alignment {
LEFT = 1;
CENTER = 2;
RIGHT = 3;
}
}
}
}
```
before this change would generate a type `Box_Element_Image_Alignment`.  Now with this change it will allow the ability to remove the extra snake casing on the type names and generate `BoxElementImageAlignment`.
> feat: option useSnakeTypeName

- integration/grpc-js/simple.ts
- src/generate-grpc-js.ts
Changes Channel Options type to Client Options and removes 2 not used imports
Fixes #693
> feat: change channel options to client options in generate grpc/js

- src/generate-nice-grpc.ts
Considering the fact that [Buf](https://buf.build) is gaining popularity and that their [default lint](https://docs.buf.build/tour/lint-your-api) configuration expects a "Service" suffix, it might be nice to avoid adding it to `nice-grpc`'s interface name automatically.
Also, in Google's Resource Oriented Design documentation, services are suffixed with "Service" ([here](https://cloud.google.com/apis/design/resource_names#resource_name_as_string), `service LibraryService`).
If you prefer, I can implement it using an option (`--ts_proto_opt=niceGrpcServiceSuffix`).
> feat: conditionally add "Service" to nice-grpc's generated service interface name

- integration/grpc-web-no-streaming-observable/example.ts
- integration/grpc-web-no-streaming/example.ts
- integration/grpc-web/example.ts
- src/generate-grpc-web.ts
> fix: return grpc-web response without toObject method

- src/main.ts
Possible fix for #739. I'm not sure how to generate code using `buf` and my fork. Can someone help with this?
> fix: Fix codegen for google.protobuf.Struct with useMapType=true

- integration/oneof-unions-snake/google/protobuf/struct.ts
- integration/oneof-unions/google/protobuf/struct.ts
- integration/oneof-unions/oneof.ts
- integration/use-readonly-types/google/protobuf/struct.ts
- integration/use-readonly-types/use-readonly-types.ts
- src/main.ts
Updates the `encode` method to generate a `switch` statement for oneof unions.  These are currently generating as `if` statements for every possible `$case` so not great for performance as the number of cases grows.
In our usage scenario we have a oneof with 160+ cases, which is currently generating 160+ `if` statements and during `encode` each is evaluated!!!
From benchmarking against our internal `.proto` message definition the `switch` version achieves ~2.8x better performance over the current `if` version.
**Before**
```typescript
export const Value = {
encode(message: Value, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
if (message.kind?.$case === "null_value") {
writer.uint32(8).int32(message.kind.null_value);
}
if (message.kind?.$case === "number_value") {   // not an …
```
> perf: generate switch statement for oneof union encode

- integration/grpc-web-no-streaming-observable/example.ts
- integration/grpc-web-no-streaming-observable/parameters.txt
- integration/grpc-web/example.ts
- integration/grpc-web/parameters.txt
- src/generate-grpc-web.ts
- src/generate-services.ts
https://github.com/stephenh/ts-proto/pull/731 introduces the `useAbortSignal` option but it's currently not implemented for grpc-web.
This PR add useAbortSignal for grpc-web, fully working with unary/invoke
> feat: implementation of useAbortSignal option for grpc-web

- integration/grpc-web-no-streaming-observable/example.ts
- src/generate-grpc-web.ts
https://github.com/stephenh/ts-proto/pull/777 introduce abort for grpc web but I forgot to change argument order for one fonction, here is the fix. I'm really sorry about that, everything tested locally and working this time.
> fix: implement abort grpc web

- integration/groups/test.ts
- integration/unknown-fields/google/protobuf/compiler/plugin.ts
- integration/unknown-fields/google/protobuf/descriptor.ts
- integration/unknown-fields/options.ts
- integration/unknown-fields/something/something.ts
- src/main.ts
Hopefully this one should merge automatically after the initialize fields PR
For a sample file with 600 repeated unknown fields, it bumps the performance from 528 ops/sec to 11,100 ops/sec (20x)
(Should be my last PR for a while (with maybe the exception of the $type issue, thank you for your time)
> perf: use array.push to prevent reallocation on every field

- integration/groups/groups-test.ts
- integration/groups/parameters.txt
- integration/groups/test.ts
- integration/unknown-fields/google/protobuf/compiler/plugin.ts
- integration/unknown-fields/google/protobuf/descriptor.ts
- integration/unknown-fields/options.ts
- integration/unknown-fields/something/something.ts
- src/generate-generic-service-definition.ts
- src/main.ts
- src/schema.ts
Makes _unknownFields a part of messages for easier access
Field left as optional as to not break existing code
Also uses `for in` as it is marginally faster than `Object.keys`
Conformant to initializeFieldsAsUndefined:
- false -> _unknownFields always created
- true -> _unknownFields created on use
> feat: include _unknownFields as a field

- README.markdown
Fix a typo in README. 
Related: #467
> docs: `useMongoObjectId` instead of `useObjectId`

- integration/grpc-web-no-streaming-observable/example.ts
- src/generate-grpc-web.ts
The AbortSignal [has a 'reason' property](http://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/reason) that can be used to pass through an exception. We should pass that on
> refactor: use the AbortSignal reason for rejection

- README.markdown
I suggest adding the note that `protobufPackage` is also skipped in the export when using the `exportCommonSymbols=false`  flag. I spent a bit too long looking for this information, and found it in some old PR or issue discussion.
This should make it easier for users to find this information, as they can just search the page for `protobufPackage`.
> docs: update README with protobufPackage note

- integration/async-iterable-services-abort-signal/simple.ts
- integration/async-iterable-services/simple.ts
- integration/avoid-import-conflicts/simple.ts
- integration/batching-with-context-esModuleInterop/batching.ts
- integration/batching-with-context/batching.ts
- integration/batching/batching.ts
- integration/generic-metadata/hero.ts
- integration/grpc-web-go-server/example.ts
- integration/lower-case-svc-methods/math.ts
- integration/meta-typings/simple.ts
- integration/no-proto-package/no-proto-package.ts
- integration/options/options.ts
- integration/simple-optionals/simple.ts
- integration/simple-prototype-defaults/simple.ts
- integration/simple-snake/simple.ts
- integration/simple-unrecognized-enum/simple.ts
- integration/simple/simple.ts
- integration/unknown-fields/options.ts
- integration/use-date-true/use-date-true.ts
- integration/wrappers-regression/wrappers-regression.ts
- src/generate-services.ts
The service ID (for example, "simple.Echoer") is currently hidden within the constructor of the service implementation.
While it's possible to override the service ID with a constructor parameter, we should also export this ServiceID constant so that it can be used elsewhere.
> feat: expose service name as separate exported constant

- src/plugin.ts
Closes https://github.com/stephenh/ts-proto/issues/853.
> fix: don't generate transitively imported files for mapped imports

- package.json
Only a small minority of users (if any) need the dataloader dependency for client-side de-N+1-ing of RPC calls.
> fix: Move dataloader to a devDependency.

- integration/grpc-js-use-date-false/grpc-js-use-date-false.ts
- integration/grpc-js-use-date-string/grpc-js-use-date-string.ts
- integration/grpc-js-use-date-true/grpc-js-use-date-true.ts
- integration/grpc-js/simple.ts
- src/generate-grpc-js.ts
Fixes #920.
This PR adds the `t:` prefix to gRPC generation imports when the import is only a type.
This makes sure that the TypeScript compiler is happy when [`verbatimModuleSyntax`](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax) is enabled 🙂
> fix: Update type imports syntax on gRPC generation

- integration/map-bigint-optional/test.ts
- integration/simple-long-bigint/google/protobuf/timestamp.ts
- integration/simple-long-bigint/google/protobuf/wrappers.ts
- integration/simple-long-bigint/numbers-long-string-test.ts
- integration/simple-long-bigint/simple.ts
- src/main.ts
Input validation for too large int64 and uint64 values when using
the compiler option forceLong=bigint.
> feat: add bigint input validation

- integration/enums-as-literals-with-string-enums/enums-as-literals-with-string-enums.ts
- integration/enums-as-literals/enums-as-literals.ts
- src/enums.ts
this pull request adds code for generating a namespace of type declarations for enums as literals that let you use them like regular enums:
old:
```ts
let foo: typeof Foo.Bar
```
new:
```ts
let foo: Foo.Bar
```
this means a library that was previously using `ts-proto` without the `enumsAsLiterals=true` can add it with less breakages.
---
`Foo.proto`
```proto
enum Foo {
Bar = 0;
Baz = 1;
Qux = 2;
}
```
old generated `Foo.ts`
```ts
export const Foo = { Bar: 0, Baz: 1, Qux: 2, UNRECOGNIZED: -1 } as const;
export type Foo = typeof Foo[keyof typeof Foo];
```
new generated `Foo.ts`
```ts
export const Foo = { Bar: 0, Baz: 1, Qux: 2, UNRECOGNIZED: -1 } as const;
export type Foo = typeof Foo[keyof typeof Foo];
export namespace Foo {
export type Bar = typeof Foo.Bar;
export type Baz = typeof …
```
> feat: generate type namespaces for enums as literals

- integration/grpc-web-abort-signal/example.ts
- integration/grpc-web/example.ts
- src/generate-grpc-web.ts
grpc-web throw an error if you close the client after it's already been closed:
https://github.com/improbable-eng/grpc-web/blob/1d9bbb09a0990bdaff0e37499570dbc7d6e58ce8/client/grpc-web/src/client.ts#L327
This can happen with the abort signals if the observer is finished first and then the abort signal is triggered, causing an exception. Here I'm changing the code generator to remove the abort signal listener in the observer finish handler.
> fix: Don't close client if we've already aborted

- README.markdown
They have been removed in 3219cdfc91976fa9149ff1f0962296f20968569a.
> fix: do not mention :local scripts

- integration/grpc-js-use-date-false/grpc-js-use-date-false.ts
- integration/grpc-js-use-date-string/grpc-js-use-date-string.ts
- integration/grpc-js-use-date-true/grpc-js-use-date-true.ts
- integration/grpc-js/simple.ts
- src/generate-grpc-js.ts
Currently type exported by generated code does not match the return value of `makeConstructor` function from grpc-js
https://github.com/grpc/grpc-node/blob/c5d35fe22db9503fb7ec2f03370cfc1723efe6e8/packages/grpc-js/src/make-client.ts#L124
because it's missing  the `serviceName` field
https://github.com/grpc/grpc-node/blob/c5d35fe22db9503fb7ec2f03370cfc1723efe6e8/packages/grpc-js/src/make-client.ts#L94
This PR adds `serviceName` field to the generated type.
> fix: add serviceName to grpc-js client constructor type

- integration/nestjs-metadata-grpc-js/hero.ts
- src/main.ts
- src/options.ts
- src/utils.ts
- tests/options-test.ts
> fix: Allow other services with nestJs.

- integration/handle-error-in-default-service/handle-error-test.ts
- integration/handle-error-in-default-service/simple.ts
- integration/handle-error-with-after-response/handle-error-test.ts
- integration/handle-error-with-after-response/simple.ts
- src/generate-services.ts
Small issue noticed with the behavior of the default service implementation `handleError` method. If the throw error was an instance of Error, then the handleError function is called correctly. However, if it was not, we had a check that prevented `handleError` from called. This isn't desired behavior as errors can be strings. 
Tested in a consuming application and this issue is resolved. Unit tests have been updated and are passing.
> fix: error handling on non-`Error` type errors

- docker-compose.yml
When running build/test process on arm machines (M1 etc), the docker-compose setup attempts to run arm images. This in turn causes protoc to fail as the `Dockerfile.protoc` forces use of protoc-x86.
This PR updates the `docker-compose.yml` file to ensure amd64 platform base images are used when running.
Before:
```
$ yarn build:test
[+] Building 1.1s (10/11)                                                                                                                                                                                    docker:desktop-linux
=> [protoc internal] load build definition from protoc.Dockerfile                                                                                                                                                           0.0s
=> => …
```
> fix: ensure docker-compose platform is amd64

- integration/before-after-request-streaming/example.ts
- integration/handle-error-in-default-service/simple.ts
- integration/handle-error-with-after-response/simple.ts
- src/generate-services.ts
`handleError` receives and returns an instance of `Error`. However, if there is a proto message named `Error` that is declared or  imported into this file, then we run into a Typescript problem. This PR forces the `handleError` function to always expect `globalThis.Error` instead.
> fix: use `globalThis.Error` in case there is a proto `Error` message

- src/main.ts
Addresses issue #1002, where there is a conflict in the generated ts.
cc @arnidan, who originally filed the issue.
> fix: Don't export `ServerStreamingMethodResult` when `outputIndex=true`

- README.markdown
Add a section to the documentation that shows some TypeScript types that could be useful in working with union-style oneOfs. I've written these a few times in different projects so I could properly type helper functions that operate on generated oneOfs, and I figured it might be useful to other users of ts-proto.
As an example, given the following:
```ts
interface MusicPlayerRequest {
command?:
| { $case: "start"; start: StartCommand }
| { $case: "stop"; stop: StopCommand }
| { $case: "next"; list: NextCommand }
| undefined; 
}
```
Then the helpers can be used like this:
```ts
type MusicPlayerCommandNames = OneOfCases<MusicPlayerRequest['command']>; // = "start" | "stop" | "next"
type MusicPlayerCommands = OneOfValues<MusicPlayerRequest['command']>; // = StartCommand | StopCommand | …
```
> Document type helpers for oneOfs

- README.markdown
ref: https://github.com/stephenh/ts-proto/pull/1023
In previous helper, it is not possible to construct a message with the oneof field passed as a function argument.
This helper allows for strict type checking and construct message using oneof fields as an argument.
Example
```proto
syntax = "proto3";
package logs;
message SignUp {
string name = 1;
}
message Login {
string account_id = 1;
}
message Logout {
string account_id = 1;
string reason = 2;
}
message LogPayload {
string created_at = 1;
oneof payload {
SignUp signup = 2;
Login login = 3;
Logout lougout = 4;
}
}
```
```typesecript
// pass by argument
foo<P extends PaloadNames>(
payload: OneOfValue<LogPayload['payload'], P>
) {
const req: LogPayload = {
createdAt: new Date().toUTCString(),
payload,
};
send(req);
}
```
```typescript …
```
> docs: add OneofValue type helper

- package.json
- yarn.lock
Updates tsx to suppress these `ExperimentalWarning` messages when running the integration tests, in order the make the output more concise and less noisy.
| before | after |
| -------- | ------- |
| ![image](https://github.com/stephenh/ts-proto/assets/10575019/bc18ca18-7b54-4921-8d30-82b415f4ea3e)  |  ![image](https://github.com/stephenh/ts-proto/assets/10575019/872f138f-3bba-44ae-a5da-f22fdbbb4fe9)  |
> chore(deps): update tsx

- src/case.ts
- tests/case-test.ts
`camelToSnake()` is converting the example string "TestAPI" -> "TEST_AP_I" when converting a 3rd party integration proto files that I am attempting to generate with the Nest option. I believe that the conversion should respect the "API" part of the string and not split it into two parts like so. 
I swapped the logic to use the already imported "case-anything" library's `snakeCase()` function as `snakeCaseAnything()` and added a couple of simple tests to ensure the logic.
I would love for this fix to go through as it is a pretty inconvenient problem at the moment (:
Thanks!
> fix: camelToSnake to respect uppercase words, such as "GetAPIValue" -> "GET_API_VALUE"

- README.markdown
The discriminated union output of `oneof=unions` and `oneof=unions-value` is incorrectly described as an Abstract Data Type. Describe as Algebraic Data Type instead.
> docs: Describe `oneof=unions-value` output as Algebraic Data Type

- src/main.ts
> fix: Incorrect message names in the generated code for repeated fields

- integration/test-1110/test-1110-test.ts
- integration/test-1110/test-1110.proto
- integration/test-1110/test-1110.ts
- src/visit.ts
"Function" is builtin, but anything prefixed or suffixed for whatever reason shouldn't be handled the same way. So check if the final result is in builtin list, not the original unmodified name
I have concerns about maybeSnakeToCamel being called earlier now, but i can't find any tests for options.snakeToCamel.includes("keys") so i'm not sure if i broke anything
```
/** Converts `key` to TS/JS camel-case idiom, unless overridden not to. */
💡export function maybeSnakeToCamel(key: string, options: Pick<Options, "snakeToCamel">): string {
if (options.snakeToCamel.includes("keys") && key.includes("_")) {
return snakeToCamel(key);
} else {
return key;
}
}
```
But all tests pass
> fix: Unbreak a use case for #1110 / fix for #1121

- integration/oneof-unions-value/oneof.ts
- integration/oneof-unions/oneof.ts
- integration/use-readonly-types/use-readonly-types.ts
- src/main.ts
This PR tweaks the output from #1136 slightly to avoid adding the trailing `//` after the union member separator if there isn't a documentation comment for the following oneof field (or if comments are turned off).
> feat: Avoid adding empty trailing comments to oneof unions

- integration/oneof-unions-snake/google/protobuf/struct.ts
- integration/oneof-unions-value/google/protobuf/struct.ts
- integration/oneof-unions-value/oneof.ts
- integration/oneof-unions/google/protobuf/struct.ts
- integration/oneof-unions/oneof.ts
- integration/use-readonly-types/google/protobuf/struct.ts
- integration/use-readonly-types/use-readonly-types.ts
- src/main.ts
In oneof scenarios, this commit proposes generating "else if" statements where applicable.
The original idea was an attempt to speed up Typescript compilation by reducing the amount of paths Typescript can analyze. Spoiler alert => nothing changes from that point of view.
The compilation of my [proto file](https://github.com/workadventure/workadventure/blob/develop/messages/protos/messages.proto) takes between 41 and 44 seconds with and without "else if" statements.
Still, the "else if" conditions should slightly speed up the runtime execution, by avoiding unnecessary checks to the Javascript runtime.
This PR is directly linked to https://github.com/stephenh/ts-proto/issues/1135
Note: in https://github.com/stephenh/ts-proto/issues/1135, @stephenh you recommend trying to use a switch …
> perf: Generating "else if" where applicable

- README.markdown
In this basic grpc implementation example `serialize` callback is not correct and throws error in testing it. I have update `serialize` with `Buffer.from` which is working fine.
> fix: update basic grpc implementation

- package.json
The build path was updated [here](https://github.com/stephenh/ts-proto/commit/3ecd4986063952ae06c6136fbd9ae0cfc75212d8), but the path for the types was not. This fixes the issue so you can import these types again.
> fix: types export path

- integration/extensions/extensions-test.ts
- integration/extensions/test.ts
- integration/meta-typings-as-const/google/protobuf/descriptor.ts
- integration/options/google/protobuf/descriptor.ts
- integration/unknown-fields/google/protobuf/descriptor.ts
- integration/use-optionals-deprecated-only/test.ts
- integration/vector-tile/vector_tile.ts
- src/main.ts
- src/types.ts
See https://protobuf.dev/editions/features/#repeated_field_encoding
In this PR, avoid encoding fields as packed when it shouldn't.
Decoding still supports both packed/unpacked fields.
See.
https://github.com/stephenh/ts-proto/issues/1207
> fix: Honour packed repeated fields encoding
